CREATE TABLE USUARIO
(
  ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  NOME VARCHAR(255) NOT NULL,
  CPF  VARCHAR(14),
  SALARIO DECIMAL(15,2) NOT NULL
)

CREATE TABLE ITEM
(
    ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
)

CREATE TABLE MOVIMENTACAO_ABERTA
(
    ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    HISTORICO VARCHAR(255) NOT NULL,
    VALOR DECIMAL(15,2) NOT NULL,
    DC VARCHAR(1) NOT NULL,
    DATALANCAMENTO DATE NOT NULL, 
    IDITEM INT NOT NULL

    CONSTRAINT FK_IDITEM FOREIGN KEY (IDITEM) REFERENCES ITEM(ID)
)